//! Model pricing: an embedded LiteLLM snapshot used for deterministic local
//! cost calculation.
//!
//! Rates are integer microdollars per token (`$3/MTok` == `3 µ$/tok`), so
//! `tokens × rate` is exact i64/i128 math with no float error. The snapshot
//! is regenerated by `scripts/refresh-pricing.py` and committed; lookups
//! normalize model names (case, vendor prefix, trailing date suffix) and
//! an unknown model is reported as unpriced rather than guessed.

use std::collections::HashMap;
use std::sync::OnceLock;

use anyhow::Result;
use serde::Deserialize;

use super::Money;

/// Cost rates for one model, µ$ per token.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rate {
    pub input: Option<i64>,
    pub output: Option<i64>,
    pub cache_read: Option<i64>,
    pub cache_creation: Option<i64>,
}

#[derive(Debug, Deserialize)]
struct Snapshot {
    #[allow(dead_code)]
    source: String,
    models: HashMap<String, SnapshotEntry>,
}

#[derive(Debug, Deserialize)]
struct SnapshotEntry {
    #[serde(default)]
    input: Option<i64>,
    #[serde(default)]
    output: Option<i64>,
    #[serde(default)]
    cache_read: Option<i64>,
    #[serde(default)]
    cache_creation: Option<i64>,
}

/// Embedded pricing catalog, parsed once on first use.
pub fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let bytes = EmbeddedSnapshot::get("pricing_snapshot.json.gz")
            .expect("pricing snapshot is embedded at build time");
        let cursor = std::io::Cursor::new(bytes.data.as_ref());
        let decoder = flate2::read::GzDecoder::new(cursor);
        let snapshot: Snapshot =
            serde_json::from_reader(decoder).expect("embedded pricing snapshot must deserialize");
        Catalog {
            models: snapshot
                .models
                .into_iter()
                .map(|(name, entry)| {
                    let pricing = ModelPricing {
                        input: entry.input,
                        output: entry.output,
                        cache_read: entry.cache_read,
                        cache_creation: entry.cache_creation,
                    };
                    (name.to_ascii_lowercase(), pricing)
                })
                .collect(),
        }
    })
}

use rust_embed::RustEmbed;

#[derive(RustEmbed)]
#[folder = "src/usage/snapshot"]
struct EmbeddedSnapshot;

/// Pricing for one model; `None` means that token class is not published and
/// the corresponding event is unpriced.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ModelPricing {
    pub input: Option<i64>,
    pub output: Option<i64>,
    pub cache_read: Option<i64>,
    pub cache_creation: Option<i64>,
}

impl ModelPricing {
    pub fn rate(self) -> Rate {
        Rate {
            input: self.input,
            output: self.output,
            cache_read: self.cache_read,
            cache_creation: self.cache_creation,
        }
    }
}

pub struct Catalog {
    models: HashMap<String, ModelPricing>,
}

impl Catalog {
    /// Look up a model by transcript name. Tries the exact name, then a
    /// vendor-qualified entries whose trailing segment matches
    /// (`anthropic/claude-sonnet-4` for `claude-sonnet-4`) only when every
    /// matching catalog entry has the same price, then the name with a
    /// trailing `-YYYYMMDD` date suffix stripped.
    pub fn lookup(&self, model: &str) -> Option<ModelPricing> {
        let name = model.trim().to_ascii_lowercase();
        if name.is_empty() {
            return None;
        }
        if let Some(found) = self.models.get(&name) {
            return Some(*found);
        }
        if let Some(pricing) = self.unique_segment_match(&name) {
            return Some(pricing);
        }
        let stripped = strip_date_suffix(&name);
        if stripped != name {
            if let Some(found) = self.models.get(&stripped) {
                return Some(*found);
            }
            if let Some(pricing) = self.unique_segment_match(&stripped) {
                return Some(pricing);
            }
        }
        None
    }

    fn unique_segment_match(&self, model: &str) -> Option<ModelPricing> {
        let mut matches = self
            .models
            .iter()
            .filter(|(key, _)| key.rsplit('/').next() == Some(model))
            .map(|(_, pricing)| *pricing);
        let first = matches.next()?;
        matches.all(|pricing| pricing == first).then_some(first)
    }

    pub fn len(&self) -> usize {
        self.models.len()
    }

    pub fn is_empty(&self) -> bool {
        self.models.is_empty()
    }
}

/// `claude-sonnet-4-5-20250929` -> `claude-sonnet-4-5`.
fn strip_date_suffix(model: &str) -> String {
    let bytes = model.as_bytes();
    if bytes.len() > 9 {
        let (head, tail) = model.split_at(bytes.len() - 8);
        if tail.bytes().all(|b| b.is_ascii_digit()) && head.ends_with('-') {
            return head.trim_end_matches('-').to_string();
        }
    }
    model.to_string()
}

/// Cost of one billed call: `tokens × rate` in i128, converted once to µ$.
/// Returns `None` when the catalog has no rate for a non-zero token class;
/// unknown pricing is never guessed.
pub fn cost(event: &super::UsageEvent, rate: Rate) -> Option<Money> {
    let (input, output, cache_read, cache_creation) = event.billed_tokens();
    let total = priced_tokens(input, rate.input)?
        + priced_tokens(output, rate.output)?
        + priced_tokens(cache_read, rate.cache_read)?
        + priced_tokens(cache_creation, rate.cache_creation)?;
    Some(Money::from_microdollars(
        total.clamp(i64::MIN as i128, i64::MAX as i128) as i64,
    ))
}

fn priced_tokens(tokens: u64, rate: Option<i64>) -> Option<i128> {
    match (tokens, rate) {
        (0, _) => Some(0),
        (_, Some(rate)) => Some(tokens as i128 * rate as i128),
        (_, None) => None,
    }
}

/// Load the embedded snapshot outside of a request (error context for
/// tooling such as `sivtr pricing check`).
pub fn verify_embedded_snapshot() -> Result<usize> {
    let catalog = catalog();
    Ok(catalog.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_snapshot_loads_and_covers_major_models() {
        let catalog = catalog();
        assert!(
            catalog.len() > 1000,
            "snapshot should carry the LiteLLM catalog"
        );
        let claude = catalog.lookup("claude-sonnet-4-5-20250929");
        assert!(
            claude.is_some(),
            "date-suffixed Claude model should resolve"
        );
        let rate = claude.unwrap().rate();
        assert!(rate.input.is_some_and(|rate| rate > 0));
        assert!(rate.output.is_some_and(|rate| rate > 0));
    }

    #[test]
    fn lookup_matches_vendor_prefixed_entries() {
        let catalog = catalog();
        assert!(catalog.lookup("gpt-5").is_some() || catalog.lookup("gpt-4o").is_some());
        assert!(catalog.lookup("").is_none());
        assert!(catalog.lookup("not-a-real-model-xyz").is_none());
    }

    #[test]
    fn cost_math_is_exact() {
        let rate = Rate {
            input: Some(3),
            output: Some(15),
            cache_read: Some(0),
            cache_creation: Some(4),
        };
        let event = super::super::UsageEvent {
            model: "test".into(),
            input_tokens: 1_000_000,
            output_tokens: 100_000,
            cache_read_tokens: 2_000_000,
            cache_creation_tokens: 0,
            occurred_at: None,
            dedup_key: "k".into(),
        };
        let money = cost(&event, rate).expect("all token classes are priced");
        // 1e6×3 + 1e5×15 + 2e6×0 = 4.5e6 µ$ = $4.50
        assert_eq!(money.microdollars, 4_500_000);
        assert_eq!(money.format(), "$4.50");
    }

    #[test]
    fn unknown_cache_rate_does_not_get_charged_as_input() {
        let rate = Rate {
            input: Some(3),
            output: Some(15),
            cache_read: None,
            cache_creation: None,
        };
        let event = super::super::UsageEvent {
            model: "test".into(),
            input_tokens: 1,
            output_tokens: 1,
            cache_read_tokens: 2,
            cache_creation_tokens: 0,
            occurred_at: None,
            dedup_key: "k".into(),
        };
        assert!(cost(&event, rate).is_none());
    }

    #[test]
    fn strip_date_suffix_only_strips_dates() {
        assert_eq!(
            strip_date_suffix("claude-sonnet-4-5-20250929"),
            "claude-sonnet-4-5"
        );
        assert_eq!(strip_date_suffix("gpt-4o"), "gpt-4o");
        assert_eq!(strip_date_suffix("gemini-2-5-pro"), "gemini-2-5-pro");
    }
}
